#!/usr/bin/env bash
# Script that installs Nginx server
sudo apt-get update
sudo apt-get -y install nginx

# Configurarion
mkdir /etc/nginx/html

touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

# Creating the Server Block
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /etc/nginx/html;
        index index.html index.htm index.nginx.debian.html;

        server_name _;

}" > /etc/nginx/sites-available/default

# Restarting
service nginx restart
