#!/usr/bin/env bash
# Script that installs Nginx server
apt-get -y update
apt-get -y install nginx

# Adjust the firewall
sudo ufw allow 'Nginx HTTP'

# Configurarion
mkdir /etc/nginx/html

# Creating the Server Block File
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

# Creating the Server Block
echo "server {
        listen 80;
        listen [::]:80;

        root /etc/nginx/html;
        index index.html index.htm index.html;

        server_name 125574-web-01;
}" > /etc/nginx/sites-available/default

# Restarting
service nginx start
