#!/usr/bin/env bash
# Script that installs Nginx server
apt-get -y update
apt-get -y install nginx
echo > /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
killall nginx
