#!/usr/bin/env bash
# Redirecting

sudo apt-get update
sudo apt-get -y install nginx

# Configuration
mkdir /etc/nginx/html

# Creating Sample Page
echo "Hello World!" > /etc/nginx/html/index.html

string_to_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$string_to_replace/" /etc/nginx/sites-enabled/default

# Restarting
service nginx restart
