#!/usr/bin/env bash
# Script that installs Nginx server
apt-get update
apt-get -y install nginx

string_to_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$string_to_replace/" /etc/nginx/sites-enabled/default

# Restarting
service nginx restart
