#!/usr/bin/env bash
# Adding a custum nginx response header

# Installing nginx
sudo apt-get -y update
sudo apt-get -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
# Creating Sample
echo "Hello World!" > /etc/nginx/html/index.html

#redirect
string_to_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.instagram.com permanent;"
sudo sed -i "s/server_name _;/$string_to_replace/" /etc/nginx/sites-enabled/default

echo -e "Ceci n'est pas une page" > /var/www/html/404.html
string_to_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_to_replace/" /etc/nginx/sites-enabled/default
sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf

# Restart Nginx
service nginx start
