#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Installing HAProxy packages
apt-get install -y software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get -y update
apt-get install haproxy=2.6.\*

# Configuration
echo "frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 125574-web-01 34.229.186.69:80 check
    server 125574-web-02 100.24.255.118:80 check " >> /etc/haproxy/haproxy.cfg

# Restart HAproxy
service haproxy restart
