#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.

# Get today's date
now="$(date +"%d-%m-%Y").tar.gz"

# Set MySQL username and password
username="root"
password="$1"

# Dump MySQL databases to backup.sql
mysqldump --user="$username" --password="$password" --all-databases > backup.sql

# Create compressed archive of backup.sql
tar -czf "$now" "backup.sql"
