#!/usr/bin/env bash
# fixing a container so that Nginx is running as the nginx user
# Stop nginx if running
sudo service nginx stop

# Change nginx user in nginx.conf
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf

# Changing ownership of nginx directories to nginx user
chmod 644 /etc/nginx/nginx.conf

# Configuring nginx to listen on all active IPs on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Starting nginx
sudo -u nginx service nginx start
